#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include <cstring>
#define FOREACH(I, C) for(__typeof((C).begin()) I = (C).begin(); I != (C).end(); I++)

using namespace std;
typedef long long ll;
const int MOD = 1000000007;

vector<string> noSol() {
	return vector<string>(1, "NO SOLUTIONS");
}

class NumberGrid {
public:
	int a[55][55], b[55][55];
	int sc[55], sr[55];
	int f[55][55 * 9], g[55][55 * 9];
	int n, m;
	vector<string> output() {
		bool okay = true;
		for ( int i = 0; i < n; i ++ )
			for ( int j = 0; j < m; j ++ ) {
				int sum = 0;
				for ( int x = 0; x < m; x ++ )
					sum += a[i][x];
				for ( int x = 0; x < n; x ++ )
					sum += a[x][j];
				sum -= a[i][j];
				okay &= sum == b[i][j];
			}
		if ( !okay ) 
			return noSol();
		vector<string> res(n, string(m, '?'));
		for ( int i = 0; i < n; i ++ )
			for ( int j = 0; j < m; j ++ ) {
				if ( a[i][j] < 0 || a[i][j] > 9 ) 
					return noSol();
				res[i][j] = (char)('0' + a[i][j]);
			}
		return res;
	}
	vector <string> decrypt(vector <string> hundreds, vector <string> tens, vector <string> ones) {
		n = hundreds.size(), m = hundreds[0].size();
		for ( int i = 0; i < n; i ++ )
			for ( int j = 0; j < m; j ++ )
				b[i][j] = (int)(hundreds[i][j]-'0') * 100 + (int)(tens[i][j]-'0') * 10 + (int)(ones[i][j]-'0');
		int tot = 0;
		for ( int i = 0; i < n; i ++ )
			for ( int j = 0; j < m; j ++ )
				tot += b[i][j];
		if ( tot % (n + m - 1) != 0 ) return noSol();
		tot /= (n + m - 1);

		if ( tot == 0 || tot == 9 * n * m ) {
			for ( int i = 0; i < n; i ++ )
				for ( int j = 0; j < m; j ++ )
					a[i][j] = tot == 0 ? 0 : 9;

			return output();
		} 

		if ( n == 1 && m == 1 ) {
			a[0][0] = b[0][0];
			return output();
		} else if ( n == 1 || m == 1 ) {
			if ( m == 1 ) {
				m = n;
				for ( int i = 0; i < n; i ++ )
					b[0][i] = b[i][0];
			}

			for ( int i = 0; i < m; i ++ )
				if ( b[0][i] != b[0][0] ) return noSol();

			f[0][0] = 1;
			g[0][0] = 1;
			for ( int i = 0; i < m; i ++ )
				for ( int j = tot; j >= 0; j -- )
					for ( int k = 0; k <= 9; k ++ )
						if ( j >= k ) {
							f[i+1][j] = (f[i+1][j] + f[i][j - k]) % MOD;
							g[i+1][j] |= g[i][j-k];
						}
			if ( !g[m][tot] ) return noSol();
			stringstream ss;
			ss << f[m][tot] << " SOLUTIONS";
			return vector<string>(1, ss.str());
		}
		for ( int i = 0; i < n; i ++ ) {
			sr[i] = 0;
			for ( int j = 0; j < m; j ++ )
				sr[i] += b[i][j];
			sr[i] -= tot;
			if ( sr[i] % (m - 1) != 0 )
				return noSol();
			sr[i] /= m - 1;
		}
		for ( int j = 0; j < m; j ++ ) {
			sc[j] = 0;
			for ( int i = 0; i < n; i ++ )
				sc[j] += b[i][j];
			sc[j] -= tot;
			if ( sc[j] % (n - 1) != 0 ) 
				return noSol();
			sc[j] /= n - 1;
		}
		for ( int i = 0; i < n; i ++ )
			for ( int j = 0; j < m; j ++ ) 
				a[i][j] = sr[i] + sc[j] - b[i][j];
		return output();
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <string> p1, vector <string> p2, bool hasAnswer, vector <string> p3) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p1[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p2[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	NumberGrid *obj;
	vector <string> answer;
	obj = new NumberGrid();
	clock_t startTime = clock();
	answer = obj->decrypt(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p3.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << "\"" << p3[i] << "\"";
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << answer[i] << "\"";
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p3.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p3[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	vector <string> p0;
	vector <string> p1;
	vector <string> p2;
	vector <string> p3;

	{
		// ----- test 0 -----
		string t0[] = {"000","000"};
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		string t1[] = {"001","111"};
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		string t2[] = {"691","457"};
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		string t3[] = {"013","257"};
		p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
	}

	{
		// ----- test 1 -----
		string t0[] = {"0"};
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		string t1[] = {"0"};
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		string t2[] = {"3"};
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		string t3[] = {"3"};
		p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
	}


	{
		// ----- test 2 -----
		string t0[] = {"0"};
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		string t1[] = {"4"};
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		string t2[] = {"2"};
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		string t3[] = {"NO SOLUTIONS"};
		p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
	}

	{
		// ----- test 3 -----
		string t0[] = {"23333333333322333333333333333333333333333333333332","33333333343333333333333333333333334333333333443333","12222222222211221222222222222222222222222222222221","12222222222211221122222221111221222222112222222221","12222222222211221122222221111221222222112222222221","12222222222211221122222221111221222222112222222221","12222222222211221122222221111221222222112222222221","22222222232222222222222222222222223222222222232222","12222222222222222222222222222222222222222222232221","01111111111100110011111110000110111111001111111110","01111111111100110011111110000110111111001111111110","22222222232222222222222222222222223222222222332222","22222222232222222222222222222222222222222222232222","12222222222222222222222222222222222222222222222221","11111112221111111112221111111111112222111112222211","12221112222211221122222221111221222222112222222221","11111112222211111122221221111221222222111222222221","22222223333322322233332332222332333333222223333322","3333333334333333333333333333333333333333333334"
			"3333","01111111111100110011111110000110111111001111111110","01111111111100110011111110000110111111001111111110","01111111111100110011111110000110111111001111111110"};
		p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
		string t1[] = {"81221116682299220134442330000331447555001226795438","14554449915522553457764553333554770777335559027651","81221116682299229123331330011221336334111226783318","60110004461188118901120119999119225223990115672106","60110004461188118901120119999119225223990115672106","60110004461188118901120119999119225223990115672106","60110004461188118901120119999119225223990115572116","14554448805522552356663663333553660667334558916651","93333337793311331235542331111442558666112337806539","70110005571188118912220229999229226334990115683217","70110005571188118912220229999229226334990115683217","15554449916633663356665663344663660888445659028761","03443338803311431246653452233542558667333338806640","92332227782200220134442331111331337556111236795439","48998883348866896790008996677997993111778992351094","60119994461188018912220119999119115333990114573216","69999994460077997901119008899119114223999003462106","68999994460077096801108008888008004112888993461096","0344333880442255234555455333355355966733344891"
			"6540","70110005571188118912220229999229226334990115683217","70110005571188118912220229999229226334990115683217","70110005571188118912220229999229226334990115683217"};
		p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
		string t2[] = {"86336665563355332604443002299076449111996335231408","64114443341133110482254880077884227229771883012586","38558880015577557152228224411551997996118557489283","94114446671133113748854880077887553552774113045849","94114446671133113748854880077887553552774113045849","94114446671133113748854880077887553552774113045849","94114446671133113748854880077887553552774113345819","16336668893355335930009002222339772774226338567731","72992224459911991593365991188665338007885224190397","16336665563355335937776002299009772441996335234731","16336665563355335937776002299009772441996335234731","83336665560022002937773779966779772118663035231408","49669998829988691560032635522365338774229991897064","05225554485544554826665221188228994330888527453620","83003332263322302604443709966776772118663005231408","94117776671133413715554810077887883229774116342519","20777776674466776048887443300110116552007449675842","08555554452244257126698291188221994663888557456950","9744777667443311304888488007711088355277744634"
			"5849","16336665563355335937776002299009772441996335234731","16336665563355335937776002299009772441996335234731","16336665563355335937776002299009772441996335234731"};
		p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
		string t3[] = {"18888888888888881111111888888811111118888888881111","18888888888888881111188888888881111888881118888811","11111118881111111118881111111881118888111111188881","11111118881111111188811111111111118888111111188881","11111118881111111188811111111111118888111111188881","11111118881111111188811111111111118888111111188881","11111118881111111188811111111111118888111111888811","11111118881111111118888111188881111888881118888111","11111118881111111111188888888111111111888888811111","11111111111111111111111111111111111111111111111111","11111111111111111111111111111111111111111111111111","11888888881111111888881111111118888111111188881111","11111111188811188811188811111188888111111888881111","11111111188811881111111881111881888111118818881111","11111111188811811111111181111111888111111118881111","11118888881111811111111181111111888111111118881111","18881111111111881111111881111111888111111118881111","18881111111111188811188811111888888888118888888881","1888888888881111188888111111188888888811888888"
			"8881","11111111111111111111111111111111111111111111111111","11111111111111111111111111111111111111111111111111","11111111111111111111111111111111111111111111111111"};
		p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
