#include<stdio.h>
#include<string.h>
int f[3][1000];
char g[3][1000][1000],s[1000],s2[1000],c1[1000],c2[1000],c3[1000];
main()
{
    int i,j,k,n;
    freopen("t.in","r",stdin);
    scanf("%s",s2);
    n=strlen(s2);
    for(i=0,j=0;i<n;++i)
        if(s2[i]=='!')
            s[j++]='?',s[j++]='?',s[j++]='?';
        else
            s[j++]=s2[i];
    n=j;
    for(i=0;i<n;++i)
    {
        if(s[i]>='a'&&s[i]<='z')
            f[1][i]=1,g[1][i][0]=s[i];
        if(s[i]=='?')
            f[1][i]=1,g[1][i][0]='a';
    }
    for(i=2;i<=n;++i)
    {
        for(j=0;j+i-1<n;++j)
        {
            f[i%3][j]=1000000;
            int len=strlen(g[i%3][j]);
            for(k=0;k<len;++k)
                g[i%3][j][k]=0;
        }
        for(j=0;j+i-1<n;++j)
        {
            memset(c1,0,sizeof(c1));
            memset(c2,0,sizeof(c2));
            memset(c3,0,sizeof(c3));
            k=j+i-1;
            if(s[j]>='a'&&s[j]<='z')
            {
                if(s[k]>='a'&&s[k]<='z')
                {
                    if(s[j]==s[k])
                    {
                        f[i%3][j]=f[(i+1)%3][j+1]+2;
                        strcpy(g[i%3][j]+1,g[(i+1)%3][j+1]);
                        g[i%3][j][0]=s[j];
                        g[i%3][j][strlen(g[i%3][j])]=s[k];
                    }
                    else
                        f[i%3][j]=10000000;
                }
                if(s[k]=='*')
                {
                    strcpy(c1+1,g[(i+2)%3][j+1]);
                    c1[0]=s[j];
                    c1[strlen(c1)]=s[j];
                    strcpy(c2,g[(i+2)%3][j]);
                    if(f[(i+2)%3][j+1]+2<f[(i+2)%3][j]||(f[(i+2)%3][j+1]+2==f[(i+2)%3][j]&&strcmp(c1,c2)<0))
                    {
                        f[i%3][j]=f[(i+2)%3][j+1]+2;
                        strcpy(g[i%3][j],c1);
                    }
                    else
                    {
                        f[i%3][j]=f[(i+2)%3][j];
                        strcpy(g[i%3][j],c2);
                    }
                }
                if(s[k]=='?')
                {
                    f[i%3][j]=f[(i+1)%3][j+1]+2;
                    strcpy(g[i%3][j]+1,g[(i+1)%3][j+1]);
                    g[i%3][j][0]=s[j];
                    g[i%3][j][strlen(g[i%3][j])]=s[j];
                }
            }
            if(s[j]=='*')
            {
                if(s[k]>='a'&&s[k]<='z')
                {
                    strcpy(c1,g[(i+2)%3][j+1]);
                    strcpy(c2+1,g[(i+2)%3][j]);
                    c2[0]=s[k];
                    c2[strlen(c2)]=s[k];
                    if(f[(i+2)%3][j+1]<f[(i+2)%3][j]+2||(f[(i+2)%3][j+1]==f[(i+2)%3][j]+2&&strcmp(c1,c2)<0))
                    {
                        f[i%3][j]=f[(i+2)%3][j+1];
                        strcpy(g[i%3][j],c1);
                    }
                    else
                    {
                        f[i%3][j]=f[(i+2)%3][j]+2;
                        strcpy(g[i%3][j],c2);
                    }
                }
                if(s[k]=='*')
                {
                    strcpy(c1,g[(i+2)%3][j+1]);
                    strcpy(c2,g[(i+2)%3][j]);
                    strcpy(c3,g[(i+1)%3][j+1]);
                    if(f[(i+2)%3][j+1]<f[(i+2)%3][j]||(f[(i+2)%3][j+1]==f[(i+2)%3][j]&&strcmp(c1,c2)<0))
                    {
                        if(f[(i+2)%3][j+1]<f[(i+1)%3][j+1]||(f[(i+2)%3][j+1]==f[(i+1)%3][j+1]&&strcmp(c1,c3)<0))
                        {
                            f[i%3][j]=f[(i+2)%3][j+1];
                            strcpy(g[i%3][j],c1);
                        }
                        else
                        {
                            f[i%3][j]=f[(i+1)%3][j+1];
                            strcpy(g[i%3][j],c3);
                        }
                    }
                    else
                    {
                        if(f[(i+2)%3][j]<f[(i+1)%3][j+1]||(f[(i+2)%3][j]==f[(i+1)%3][j+1]&&strcmp(c2,c3)<0))
                        {
                            f[i%3][j]=f[(i+2)%3][j];
                            strcpy(g[i%3][j],c2);
                        }
                        else
                        {
                            f[i%3][j]=f[(i+1)%3][j+1];
                            strcpy(g[i%3][j],c3);
                        }
                    }
                }
                if(s[k]=='?')
                {
                    strcpy(c1,g[(i+2)%3][j+1]);
                    strcpy(c2+1,g[(i+2)%3][j]);
                    c2[0]='a';
                    c2[strlen(c2)]='a';
                    if(f[(i+2)%3][j+1]<f[(i+2)%3][j]+2||(f[(i+2)%3][j+1]==f[(i+2)%3][j]+2&&strcmp(c1,c2)<0))
                    {
                        f[i%3][j]=f[(i+2)%3][j+1];
                        strcpy(g[i%3][j],c1);
                    }
                    else
                    {
                        f[i%3][j]=f[(i+2)%3][j]+2;
                        strcpy(g[i%3][j],c2);
                    }
                }
            }
            if(s[j]=='?')
            {
                if(s[k]>='a'&&s[k]<='z')
                {
                    f[i%3][j]=f[(i+1)%3][j+1]+2;
                    strcpy(g[i%3][j]+1,g[(i+1)%3][j+1]);
                    g[i%3][j][0]=s[k];
                    g[i%3][j][strlen(g[i%3][j])]=s[k];
                }
                if(s[k]=='*')
                {
                    strcpy(c1+1,g[(i+2)%3][j+1]);
                    strcpy(c2,g[(i+2)%3][j]);
                    c1[0]='a';
                    c1[strlen(c1)]='a';
                    if(f[(i+2)%3][j+1]+2<f[(i+2)%3][j]||(f[(i+2)%3][j+1]+2==f[(i+2)%3][j]&&strcmp(c1,c2)<0))
                    {
                        f[i%3][j]=f[(i+2)%3][j+1]+2;
                        strcpy(g[i%3][j],c1);
                    }
                    else
                    {
                        f[i%3][j]=f[(i+2)%3][j];
                        strcpy(g[i%3][j],c2);
                    }
                }
                if(s[k]=='?')
                {
                    f[i%3][j]=f[(i+1)%3][j+1]+2;
                    strcpy(g[i%3][j]+1,g[(i+1)%3][j+1]);
                    g[i%3][j][0]='a';
                    g[i%3][j][strlen(g[i%3][j])]='a';
                }
            }
        }
    }
//	printf("%d\n", strlen(g[n%3][0]));
    if(f[n%3][0]<10000000)
        printf("YES\n%s\n",g[n%3][0]);
    else
        printf("NO\n");
    return 0;
}
